name: spring CICD

on:
  push:
    branches: [ 'develop' ]

env:
  AWS_REGION: ap-northeast-2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t nextjs-app .
          
      - name: Docker build & push to docker hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/eday-nextjs .
          docker push ${{ secrets.DOCKER_USERNAME }}/eday-nextjs

        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: www.eday.site
        username: ubuntu
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        script: |
          if [ "$(docker ps -qa -f name=nextjs-container)" ]; then
            docker stop nextjs-container
            docker rm nextjs-container
          fi
          docker pull ${{ secrets.DOCKER_USERNAME }}/eday-nextjs
          docker run -d --name nextjs-container -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/eday-nextjs
          docker image prune -f
